baseURL = "https://www.antonioarjona.dev/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Antonio Arjona - Quality Engineer & Web Developer"
    author = "Chemistdev"
    description = "Personal Website from Antonio Arjona"
    copyright = "©2020 Powered by"

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "light"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Antonio Arjona"
		tagline = "Software Developer"
		location = "based in North Rhine-Westphalia (Germany)"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://www.linkedin.com/in/antonio-manuel-arjona"
            title = "LinkedIn"		

        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/twochemist"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "https://twitter.com/chemistdev"
            title = "Twitter"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "A Chemist, lover of open software, embedded systems and software that move things. I am professionally connected with the automotive industry as a **QA Engineer** for lighting & electronics systems.I graduated with a master's degree in _Chemistry_ from the _University of Granada_ in ES. I am somehow __forced to become a Programmer__ to productively communicate with any Software Engineer. I dedicate my little free time to build side projects in **Web Development** and **Embedded Systems.**"

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Quality Engineer"
            dates = "2004 - *Present*"
            company = "Automotive Industry"
            details = "Lighting applications based on intensive usage of electronic and LEDs."

	  [[params.experience.list]]
            position = "Product Development"
            dates = "2003 - 2003"
            company = "Chemical Pharma Industry"
            details = "Software libraries translation for analytical instrumentation."
	  

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

         [[params.education.list]]
            degree = "M.S. in Chemistry"
            college = "University of Granada"
            dates = "1998 - 2004"
            thesis_title = "Analytical determination of alcohol content in beverages by phase titration."
            thesis_link = "#"
         [[params.education.list]]
            degree = "Study abroad, Germany"
            college = "Friedrich-Schiller-Universität Jena. Fakultät für Chemie 5.S/6.S"
            dates = "2003 - 2004"      
        [[params.education.list]]
            degree = "PGc in Polymer Materials"
            college = "UNED. Synthesis of Polymers and Processing Technologies. "
            dates = "2006 - 2009"
	  thesis_title = ""
          



    # Publication section
    [params.publication]
        title = "Programming"
        icon = "fas fa-code"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Web Technologies", "Microcontrollers", "Embedded Software"]

        [[params.publication.list]]
            title = "HTML, CSS and JavaScript frameworks (Vue.js, React, Angular)"
            authors = "Front-End Developer"
            date = "2019"
            journal = "Pixelpro"
            link = "#"
            type = "Web Technologies"

        [[params.publication.list]]
            title = "Javascript | C | Python"
            authors = "Arduino Project Hub"
            date = "2018"
            journal = "arduino.cc"
            link = "#"
            type = "Microcontrollers"
		
        [[params.publication.list]]
            title = "Coding standard C++14 | Software testing"
            authors = "C++ | Python"
            date = "2018"
            journal = "Udemy"
            link = "#"
            type = "Embedded Software"


    
    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "EMBEDDED Systems"
            url = "#"
            description = "Arduino rover autonomous navigation"
        [[params.project.list]]
            title = "E-COMMERCE Web Sites"
            url = "#"
            description = "CMS Wordpress with WooCommerce"
        [[params.project.list]]
            title = "STATIC Site Generator"
            url = "#"
            description = "CMS Hugo & Netlify"
        [[params.project.list]]
            title = "WEB Landing Pages"
            url = "#"
            description = "HTML-CSS-JS templates from scratch"      
        [[params.project.list]]
            title = "WEB Corporate Company"
            url = "#"
            description = "CMS TYPO3" 	  

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Development & Manufacturing in Automotive"
            skillrating = 80
        [[params.skill.list]]
            skill = "Software Development in Web Applications"
            skillrating = 60
        [[params.skill.list]]
            skill = "Electronics for Makers"
            skillrating = 50

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"
		
        [[params.hobby.list]]		
		    hobby = "Web Development"
        [[params.hobby.list]]		
		    hobby = "Programming"		    
        [[params.hobby.list]]		
		    hobby = "Triathlon"
        [[params.hobby.list]]		
		    hobby = "Drawing"

